### ISSUE TITLE
[Feature Request] Integrate with Sketchpacks Relay to serve auto-updates

### ISSUE THREAD

**Issue by adamkirkwood** [zeroheight/zeroheight-sketch-plugin#1]
More details found @ https://github.com/integration/sketchpacks-relay

Example
![screen shot 2017-03-22 at 4 08 57 pm](https://cloud.githubusercontent.com/assets/52746/24224720/fc40de64-0f19-11e7-8473-a2798193fc33.png)

**Comment by robintindale** [comment]
I did 😭 Can you help with why it's not working? I thought I'd give it a while incase you had an indexing job that needed to run

![image](https://cloud.githubusercontent.com/assets/2700528/24948483/59b0f770-1f62-11e7-877e-572d6970c82c.png)

everything seems to be set up correctly and I've JSONlint.com'd the manifest.json

**Comment by robintindale** [comment]
yay 🙌🏻   
it just took a while

**Comment by adamkirkwood** [comment]
Hey @robintindale. We are looking into the issue on our end.

What we've noticed is that the integration installation didn't take hold. 

If you wanted the `Auto-updates` badge to appear on your plugin within Sketchpacks, try re-installing the integration on your zeroheight/zeroheight-sketch-plugin repo.

**Comment by robintindale** [comment]
ah cool, yep I see it in the repository but there is no `Auto Updates` badge. Will give re-installing the integration a go

**Comment by robintindale** [comment]
![image](https://cloud.githubusercontent.com/assets/2700528/24975192/c3d77e80-1fbc-11e7-8830-3b0bdd37123f.png)

tasty!

**Comment by willdavis** [comment]
Hi @robintindale thanks for integrating!  Sorry you hit a snag.

Here's what I was able to figure out from the logs.  Relay detected the integration, but was unable to create the plugin in the registry.  **This was not due to any error on your part**.  Im still looking into why, but for some reason the Github API responded with a rate limit timeout part way through the background job.

This was why you were unable to see the plugin.  Since you also added it to the [sketch plugin-directory](https://raw.githubusercontent.com/sketchplugins/plugin-directory/master/plugins.json) the plugin was able to be indexed later by our daily cron jobs.

The best way to fix this for now is to remove and re-add the integration.
We have plans on the roadmap to build a dashboard for plugin developers, which will be able to get you much better feedback about the state of your plugins in the registry.
